package com.mundial.alfajores;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.util.*;import org.json.*;

public class MainActivity extends Activity{
 int crema=Color.rgb(250,242,222), choc=Color.rgb(80,45,27), oro=Color.rgb(194,138,46); LinearLayout lista; ArrayList<Alfajor> data=new ArrayList<>(); SharedPreferences sp; Uri fotoTemp=null; ImageView imgTemp; static final int PICK=77;
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("db",0);load();drawMain();}
 TextView tv(String t,int spx,int c){TextView v=new TextView(this);v.setText(t);v.setTextSize(spx);v.setTextColor(c);v.setPadding(12,8,12,8);return v;}
 Button btn(String t){Button b=new Button(this);b.setText(t);b.setTextColor(Color.WHITE);b.setBackgroundColor(oro);return b;}
 void drawMain(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,24,18,18);root.setBackgroundColor(crema);sv.addView(root);TextView title=tv("🏆 Mundial de Alfajores",28,choc);title.setGravity(1);root.addView(title);TextView sub=tv("Ranking personal",16,choc);sub.setGravity(1);root.addView(sub);Button add=btn("+ Agregar alfajor");root.addView(add,new LinearLayout.LayoutParams(-1,-2));add.setOnClickListener(v->form(null));lista=new LinearLayout(this);lista.setOrientation(LinearLayout.VERTICAL);root.addView(lista);setContentView(sv);renderList();}
 String medal(int i){return i==0?"🥇":i==1?"🥈":i==2?"🥉":"#"+(i+1);}
 void renderList(){lista.removeAllViews();Collections.sort(data,(a,b)->{int c=Double.compare(b.avg(),a.avg());if(c!=0)return c;c=Double.compare(b.sabor,a.sabor);if(c!=0)return c;c=Double.compare(b.relleno,a.relleno);if(c!=0)return c;c=Double.compare(b.cobertura,a.cobertura);if(c!=0)return c;return Long.compare(b.fecha,a.fecha);}); if(data.isEmpty()){lista.addView(tv("Todavía no hay alfajores. Agregá el primero.",18,choc));return;} for(int i=0;i<data.size();i++){Alfajor a=data.get(i);LinearLayout card=new LinearLayout(this);card.setPadding(12,12,12,12);card.setBackgroundColor(Color.WHITE);card.setOrientation(LinearLayout.HORIZONTAL);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,14,0,0);lista.addView(card,cp);TextView pos=tv(medal(i),24,choc);card.addView(pos);ImageView im=new ImageView(this);im.setBackgroundColor(Color.rgb(230,220,200));im.setScaleType(ImageView.ScaleType.CENTER_CROP);if(a.foto!=null&&!a.foto.isEmpty())im.setImageURI(Uri.parse(a.foto));card.addView(im,new LinearLayout.LayoutParams(120,120));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);card.addView(info,new LinearLayout.LayoutParams(0,-2,1));info.addView(tv(a.nombre,20,choc));info.addView(tv("Promedio: "+String.format(Locale.US,"%.2f",a.avg())+"/5",17,oro));info.addView(tv("Sabor "+stars(a.sabor)+"  Relleno "+stars(a.relleno),14,choc));card.setOnClickListener(v->detail(a));}}
 String stars(double n){String s="";for(int i=1;i<=5;i++)s+=i<=Math.round(n)?"★":"☆";return s+" "+n;}
 void detail(Alfajor a){Dialog d=new Dialog(this);ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(24,24,24,24);r.setBackgroundColor(crema);sv.addView(r);ImageView im=new ImageView(this);im.setBackgroundColor(Color.WHITE);im.setScaleType(ImageView.ScaleType.CENTER_CROP);if(a.foto!=null&&!a.foto.isEmpty())im.setImageURI(Uri.parse(a.foto));r.addView(im,new LinearLayout.LayoutParams(-1,420));r.addView(tv(a.nombre,26,choc));r.addView(tv("Promedio: "+String.format(Locale.US,"%.2f",a.avg())+"/5",20,oro));r.addView(tv("Cobertura: "+stars(a.cobertura),18,choc));r.addView(tv("Relleno: "+stars(a.relleno),18,choc));r.addView(tv("Sabor: "+stars(a.sabor),18,choc));r.addView(tv("Comentario: "+(a.comentario.isEmpty()?"-":a.comentario),16,choc));Button e=btn("Editar");Button del=btn("Eliminar");Button close=btn("Cerrar");r.addView(e);r.addView(del);r.addView(close);e.setOnClickListener(v->{d.dismiss();form(a);});del.setOnClickListener(v->{data.remove(a);save();d.dismiss();drawMain();});close.setOnClickListener(v->d.dismiss());d.setContentView(sv);d.show();}
 void form(Alfajor edit){Dialog d=new Dialog(this);ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(24,24,24,24);r.setBackgroundColor(crema);sv.addView(r);r.addView(tv(edit==null?"Agregar alfajor":"Editar alfajor",26,choc));EditText nombre=new EditText(this);nombre.setHint("Nombre");nombre.setTextColor(choc);nombre.setSingleLine();if(edit!=null)nombre.setText(edit.nombre);r.addView(nombre);imgTemp=new ImageView(this);imgTemp.setBackgroundColor(Color.WHITE);imgTemp.setScaleType(ImageView.ScaleType.CENTER_CROP);fotoTemp=edit==null?null:Uri.parse(edit.foto==null?"":edit.foto);if(fotoTemp!=null&&!fotoTemp.toString().isEmpty())imgTemp.setImageURI(fotoTemp);r.addView(imgTemp,new LinearLayout.LayoutParams(-1,360));Button foto=btn("Elegir foto");r.addView(foto);SeekBar cob=bar(r,"Cobertura",edit==null?0:edit.cobertura), rel=bar(r,"Relleno",edit==null?0:edit.relleno), sab=bar(r,"Sabor",edit==null?0:edit.sabor);EditText com=new EditText(this);com.setHint("Comentario opcional");com.setMinLines(2);if(edit!=null)com.setText(edit.comentario);r.addView(com);Button g=btn("Guardar");r.addView(g);foto.setOnClickListener(v->{Intent in=new Intent(Intent.ACTION_PICK,MediaStore.Images.Media.EXTERNAL_CONTENT_URI);startActivityForResult(in,PICK);});g.setOnClickListener(v->{if(nombre.getText().toString().trim().isEmpty()){Toast.makeText(this,"Falta nombre",0).show();return;} Alfajor a=edit==null?new Alfajor():edit;a.nombre=nombre.getText().toString().trim();a.foto=fotoTemp==null?"":fotoTemp.toString();a.cobertura=cob.getProgress()/2.0;a.relleno=rel.getProgress()/2.0;a.sabor=sab.getProgress()/2.0;a.comentario=com.getText().toString();if(edit==null){a.fecha=System.currentTimeMillis();data.add(a);}save();d.dismiss();drawMain();});d.setContentView(sv);d.show();}
 SeekBar bar(LinearLayout r,String lab,double val){TextView t=tv(lab+": "+val+"/5",18,choc);r.addView(t);SeekBar b=new SeekBar(this);b.setMax(10);b.setProgress((int)Math.round(val*2));b.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){t.setText(lab+": "+(p/2.0)+"/5 "+stars(p/2.0));}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});r.addView(b);return b;}
 public void onActivityResult(int r,int c,Intent datai){super.onActivityResult(r,c,datai);if(r==PICK&&c==RESULT_OK&&datai!=null){fotoTemp=datai.getData();if(imgTemp!=null)imgTemp.setImageURI(fotoTemp);}}
 void load(){try{JSONArray arr=new JSONArray(sp.getString("items","[]"));for(int i=0;i<arr.length();i++)data.add(Alfajor.from(arr.getJSONObject(i)));}catch(Exception e){}}
 void save(){try{JSONArray arr=new JSONArray();for(Alfajor a:data)arr.put(a.json());sp.edit().putString("items",arr.toString()).apply();}catch(Exception e){}}
 public static class Alfajor{String nombre="",foto="",comentario="";double cobertura,relleno,sabor;long fecha;double avg(){return (cobertura+relleno+sabor)/3.0;}JSONObject json()throws Exception{JSONObject o=new JSONObject();o.put("n",nombre);o.put("f",foto);o.put("c",cobertura);o.put("r",relleno);o.put("s",sabor);o.put("co",comentario);o.put("fe",fecha);return o;}static Alfajor from(JSONObject o)throws Exception{Alfajor a=new Alfajor();a.nombre=o.optString("n");a.foto=o.optString("f");a.cobertura=o.optDouble("c");a.relleno=o.optDouble("r");a.sabor=o.optDouble("s");a.comentario=o.optString("co");a.fecha=o.optLong("fe");return a;}}
}
